import { 
  faInstagram, faTiktok, faYoutube, faFacebook, faTelegram, faTwitter, 
  faSpotify, faSnapchat, faLinkedin, faWhatsapp, faTwitch, faSoundcloud,
  faVimeo, faDeezer, faGooglePlay, faKickstarter
} from '@fortawesome/free-brands-svg-icons';
import { faGlobe, faChartLine, faSearchDollar, faMobileAlt } from '@fortawesome/free-solid-svg-icons';

export const platformIcons: Record<string, any> = {
  tiktok: faTiktok,
  facebook: faFacebook,
  instagram: faInstagram,
  youtube: faYoutube,
  telegram: faTelegram,
  twitter: faTwitter,
  spotify: faSpotify,
  snapchat: faSnapchat,
  linkedin: faLinkedin,
  whatsapp: faWhatsapp,
  twitch: faTwitch,
  soundcloud: faSoundcloud,
  vimeo: faVimeo,
  deezer: faDeezer,
  'google play': faGooglePlay,
  'play store': faGooglePlay,
  'android app': faGooglePlay,
  kick: faKickstarter,
  'website traffic': faChartLine,
  coinmarketcap: faSearchDollar,
  clubhouse: faMobileAlt,
  others: faGlobe
};

export const platformColors: Record<string, string> = {
  tiktok: 'bg-black text-white',
  facebook: 'bg-[#1877F2] text-white',
  instagram: 'bg-gradient-to-tr from-[#f9ce34] via-[#ee2a7b] to-[#6228d7] text-white',
  youtube: 'bg-[#FF0000] text-white',
  telegram: 'bg-[#0088cc] text-white',
  twitter: 'bg-black text-white',
  spotify: 'bg-[#1DB954] text-white',
  snapchat: 'bg-[#FFFC00] text-black',
  linkedin: 'bg-[#0077B5] text-white',
  whatsapp: 'bg-[#25D366] text-white',
  twitch: 'bg-[#9146FF] text-white',
  soundcloud: 'bg-[#FF5500] text-white',
  vimeo: 'bg-[#1AB7EA] text-white',
  deezer: 'bg-black text-white',
  'google play': 'bg-gradient-to-r from-[#4285F4] via-[#34A853] to-[#FBBC05] text-white',
  kick: 'bg-[#53FC18] text-black',
  'website traffic': 'bg-emerald-600 text-white',
  coinmarketcap: 'bg-[#171924] text-white',
  clubhouse: 'bg-[#705e4f] text-white',
  others: 'bg-gray-500 text-white',
};

export const platformTextColors: Record<string, string> = {
  tiktok: 'text-black',
  facebook: 'text-[#1877F2]',
  instagram: 'text-[#E1306C]',
  youtube: 'text-[#FF0000]',
  telegram: 'text-[#0088cc]',
  twitter: 'text-[#1DA1F2]',
  spotify: 'text-[#1DB954]',
  snapchat: 'text-[#FFFC00]',
  linkedin: 'text-[#0077B5]',
  whatsapp: 'text-[#25D366]',
  twitch: 'text-[#9146FF]',
  soundcloud: 'text-[#FF5500]',
  vimeo: 'text-[#1AB7EA]',
  deezer: 'text-black',
  'google play': 'text-[#4285F4]',
  kick: 'text-[#53FC18]',
  'website traffic': 'text-emerald-600',
  coinmarketcap: 'text-[#171924]',
  clubhouse: 'text-[#705e4f]',
  others: 'text-gray-500',
};

export const platformBgs: Record<string, string> = {
  tiktok: 'bg-gray-100',
  facebook: 'bg-[#1877F2]/10',
  instagram: 'bg-[#E1306C]/10',
  youtube: 'bg-[#FF0000]/10',
  telegram: 'bg-[#0088cc]/10',
  twitter: 'bg-[#1DA1F2]/10',
  spotify: 'bg-[#1DB954]/10',
  snapchat: 'bg-[#FFFC00]/10',
  linkedin: 'bg-[#0077B5]/10',
  whatsapp: 'bg-[#25D366]/10',
  twitch: 'bg-[#9146FF]/10',
  soundcloud: 'bg-[#FF5500]/10',
  vimeo: 'bg-[#1AB7EA]/10',
  deezer: 'bg-gray-100',
  'google play': 'bg-emerald-50/50',
  kick: 'bg-[#53FC18]/10',
  'website traffic': 'bg-emerald-50',
  coinmarketcap: 'bg-gray-100',
  clubhouse: 'bg-orange-50',
  others: 'bg-gray-100',
};
